// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGskWsqP1j_ztzWCPCxcgYwapBY1up60I',
    appId: '1:541746469592:web:6042f95dca1cb87ba215ad',
    messagingSenderId: '541746469592',
    projectId: 'memorise-910c3',
    authDomain: 'memorise-910c3.firebaseapp.com',
    storageBucket: 'memorise-910c3.appspot.com',
    measurementId: 'G-C3KK1EP48E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-Jw6QHd7OcT_BIn7t5CzvOuXbHGBuF4',
    appId: '1:541746469592:android:f74e1a6f315c9993a215ad',
    messagingSenderId: '541746469592',
    projectId: 'memorise-910c3',
    storageBucket: 'memorise-910c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA-Z6NCc9-RdllKe5WSlJE0EeKE3uz5a8',
    appId: '1:541746469592:ios:38d5ac2002f104c9a215ad',
    messagingSenderId: '541746469592',
    projectId: 'memorise-910c3',
    storageBucket: 'memorise-910c3.appspot.com',
    iosBundleId: 'com.example.memoriseMobile',
  );
}
